export const TEMPLATE_LIST_REQUEST = 'TEMPLATE_LIST_REQUEST'
export const TEMPLATE_LIST_SUCCESS = 'TEMPLATE_LIST_SUCCESS'
export const TEMPLATE_LIST_FAIL = 'TEMPLATE_LIST_FAIL'


export const TEMPLATE_DETAILS_REQUEST = 'TEMPLATE_DETAILS_REQUEST'
export const TEMPLATE_DETAILS_SUCCESS = 'TEMPLATE_DETAILS_SUCCESS'
export const TEMPLATE_DETAILS_FAIL = 'TEMPLATE_DETAILS_FAIL'



export const TEMPLATE_DELETE_REQUEST = 'TEMPLATE_DELETE_REQUEST'
export const TEMPLATE_DELETE_SUCCESS = 'TEMPLATE_DELETE_SUCCESS'
export const TEMPLATE_DELETE_FAIL = 'TEMPLATE_DELETE_FAIL'